project/gallery/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Optional
from flask_wtf.file import FileField, FileAllowed, FileRequired
from project import images


class AddImageForm(FlaskForm):
    image = FileField('Recipe Image', validators=[FileRequired(), FileAllowed(images, 'Images only!')])
    image_title = StringField('Title', validators=[DataRequired()])
    image_description = StringField('Description', validators=[Optional()])
    submit = SubmitField('Add')


class EditImageForm(FlaskForm):
    image_title = StringField('Title', validators=[DataRequired()])
    image_description = StringField('Description', validators=[Optional()])
    submit = SubmitField('Update')

project/gallery/__init__.py
"""
The gallery Blueprint handles displaying images.
"""
from flask import Blueprint
gallery_blueprint = Blueprint('gallery', __name__, template_folder='templates')

from . import routes

project/gallery/routes.py
#################
#### imports ####
#################

from flask import render_template, url_for, request, flash, redirect
from flask_login import login_required

from . import gallery_blueprint
from .forms import AddImageForm, EditImageForm
from project.models import Image
from project import images, db


################
#### routes ####
################

@gallery_blueprint.route('/images')
@login_required
def gallery():
    image_gallery = Image.query.all()
    return render_template('gallery/images.html', images=image_gallery)


@gallery_blueprint.route('/image/<image_id>')
def image_view(image_id):
    image = Image.query.filter_by(id=image_id).first_or_404()
    return render_template('gallery/image_view.html', image=image)


@gallery_blueprint.route('/add_image', methods=['GET', 'POST'])
@login_required
def add_image():
    # Cannot pass in 'request.form' to AddImageForm constructor, as this will cause 'request.files' to not be
    # sent to the form.  This will cause AddImageForm to not see the file data.
    # Flask-WTF handles passing form data to the form, so not parameters need to be included.
    form = AddImageForm()

    if request.method == 'POST' and form.validate_on_submit():
        filename = images.save(request.files['image'])
        url = images.url(filename)
        new_image = Image(filename, url, form.image_title.data, form.image_description.data)
        db.session.add(new_image)
        db.session.commit()
        flash(f'New image, {form.image_title.data}, added!')
        return redirect(url_for('gallery.gallery'))

    return render_template('gallery/add_image.html', form=form)


@gallery_blueprint.route('/edit_image/<image_id>', methods=['GET', 'POST'])
@login_required
def edit_image(image_id):
    form = EditImageForm()
    current_image = Image.query.filter_by(id=image_id).first_or_404()

    if form.validate_on_submit():
        current_image.title = form.image_title.data
        current_image.description = form.image_description.data
        db.session.add(current_image)
        db.session.commit()
        flash(f'Image, {form.image_title.data}, has been updated!')
        return redirect(url_for('gallery.gallery'))

    return render_template('gallery/edit_image.html', form=form, image=current_image)


@gallery_blueprint.route('/delete_image/<image_id>', methods=['GET', 'POST'])
@login_required
def delete_image(image_id):
    current_image = Image.query.filter_by(id=image_id).first_or_404()
    image_title = current_image.title
    db.session.delete(current_image)
    db.session.commit()
    flash(f'Image ({image_title}) was deleted.')
    return redirect(url_for('gallery.gallery'))

project/gallery/templates/gallery/add_image.html
{% extends "base.html" %}

{% block content %}
    <h1>Add Image</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {{ form.hidden_tag() }}

        <p>
            {{ form.image.label }}<br>
            {{ form.image }}<br>
            {% for error in form.image.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.image_title.label }}<br>
            {{ form.image_title(size=40) }}<br>
            {% for error in form.image_title.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.image_description.label }}<br>
            {{ form.image_description(size=80) }}<br>
            {% for error in form.image_description.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

project/gallery/templates/gallery/edit_image.html
{% extends "base.html" %}

{% block extra_styling %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style_image_view.css') }}">
{% endblock %}


{% block content %}
    <div class="imageDisplay">
        <img src="{{ image.filename_with_path }}" alt="{{ image.title }}">
    </div>

    <form action="" method="post">
        {{ form.hidden_tag() }}

        <div class="imageTitle">
            <h3>Title:</h3>
            <input type="text" id="image_title" name="image_title" value="{{ image.title }}">
        </div>

        <div class="imageDate">
            <h3>Date: {{ image.date_created }}</h3>
        </div>

        <div class="imageDescription">
            <h3>Description:</h3>
            <input type="text" id="image_description" name="image_description" value="{{ image.description }}">
        </div>

        <div class="imageEvent">
            <h3>Event: ________</h3>
        </div>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

project/gallery/templates/gallery/image_view.html
{% extends "base.html" %}

{% block extra_styling %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style_image_view.css') }}">
{% endblock %}


{% block content %}
    <div class="imageDisplay">
        <img src="{{ image.filename_with_path }}" alt="{{ image.title }}">
    </div>

    <div class="imageTitle">
        <h2>Title: {{ image.title }}</h2>
    </div>

    <div class="imageDate">
        <h2>Date: {{ image.date_created }}</h2>
    </div>

    <div class="imageDescription">
        <h2>Description: {{ image.description }}</h2>
    </div>

    <div class="imageEvent">
        <h2>Event: ________</h2>
    </div>

    <a href="{{ url_for('gallery.edit_image', image_id=image.id) }}">Edit</a>
    <a href="{{ url_for('gallery.delete_image', image_id=image.id) }}">Delete</a>

{% endblock %}

project/gallery/templates/gallery/images.html
{% extends "base.html" %}

{% block extra_styling %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style_image_gallery.css') }}">
{% endblock %}


{% block content %}
    {% for image in images %}
        <div class="card">
            <a href="{{ url_for('gallery.image_view', image_id=image.id) }}"><img src="{{ image.thumbnail_with_path }}" alt="{{ image.title }}"></a>
            <div class="card_text">
                <h4>{{ image.title }}</h4>
            </div>
        </div>
    {% endfor %}
{% endblock %}